# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 54ac6af94a89a9760d79d98d681e586a84ba7183eea4331be3e29c572394e2992b0d46c5120f6309cc3a5cb67d80089977adfb5347ee94c3eeb1cace24015e1a

test:
  secret_key_base: b9c666aa8f168972e7e2e709d07c96e8fe63c334d62b3f1ffb62991c2c3f3d9420540f102296e9a156bf1b55140db0cf2e03c49aad09485d7bc813298dada017

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
